### PR TITLE
feat(auth): Add authentication module (`replit.auth`)

### PR DESCRIPTION
**Pull request by DaInfLoop**
Why
===

I saw that there was a [Node.js module](https://npm.im/@replit/repl-auth) for this, and [a template on Replit](https://replit.com/@replit/Python-Flask-ReplAuth?v=1) for it, but yet no proper module for it.

What changed
============

- Added the authentication module, can be used with either:
```py
from replit.auth import getUserInfo
```
```py
# I understand this might not be the best way but it works
from replit import getUserInfo
```
- Updated the pyproject version
- Slightly updated the `.gitignore` file to ignore Replit-specific config files, such as `.replit` and `replit.nix`

Test plan
=========

I did test this in a different Repl, which may be a bit annoying to test with - I can setup a test file if needed however.

Rollout
=======

- [X] This is fully backward and forward compatible

### CODE REVIEW

**Review by noneofyourbusiness1415252 — COMMENTED** [review]
please [format the code](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AVLAk1dAD2IimZxl1N_Wk8FsHgefxOIHALqp6RhP_xnyoXldfV1YScUiSyBLnd3CrVFMcIZatj9ylTmQNSwCQSgds3rwUzn4RF-kjsX0YMh7xIRw1NvUg44qJmRzI0Z_tHp-c9oRO8vDXTpu05GIFVxOfZn7dX0UW7nTzOoMvastBHIkSr7D5pEcqLzV7Wz_oSTzK3il5QFAePDwrPL0isID5cxWoEfqr9hVg24asmSZQO_x3h-lSwiiYfFM73Zc3OYouk4OVJxbvyT_d9kfMQXYJpPj39eSIfIKv9qmEWVZUx2GATJjWxIa9pO0SvcYkHJysoLAi0fetmMIy-txvF662jRBFrTA7jsICQ-LsfmG7zGqntQ0JJTPQESQE7oNC_YC_QGX-vef8F7V0f-tzbAhSrDzS7IUu179j-zu9s4i0VfvBu1qg10j8xGXWKJTthZl7yBU26BP-uFbi1QAblN-1DmopBmsqPNijMbohvYe4MdHTDETKr7Wy-QYDgJMxYlTIvhQzQLOpNQIJyQj93LpD4EHpEYO7HH2AviAZV7F3H94lY0AQTP3WuuNHhtcMyoldBMfJS7oM7bs7OMaKvvV8gJ64C7KDWhqrJn4aMqAI29KD-xD7VozCbwqv9HDjegDzHvyyr608yTJ7cQTyHl-SiKzMghvbq3bwxmmZyKDIe5ZaeDB36OQiR9HhNBiklHN1YrV6EWSsk0SiIfrgs68mm8NIZLoyYJdejTpHCpPqJpOWpkrjrKbJBf8Qgm5_TuTUkhcINBYwvzibxsxfi8xYQAAAAAiheXTQom4sAAAekEzAoAAD_skjaxxGf7AgAAAAAEWVo=)
some tips:
1. You can set attributes in the class body directly:
```py
class User:
    id = name = bio = profile_image = roles = teams = url = None
```
2. No need to convert `filter(...)` or `request.headers` to a `list` when you're just using it in a for loop.
3. `REPLIT_HEADERS` looks like it's a constant because it's SCREAMING.
4. `x if x else ""` ❌ `x or ""` ✅ 
5. (debatable) `return x if y else None` ❌ 
```py
    if x:
        return y
```
6. `x == y or x == z` :x: `x in {y, z}` ✅

**Comment by DaInfLoop** [comment]
Will do - the code formatting is because my Replit settings are for 2 spaces instead of 4 (which this repo uses)

1) Interesting, will update
2) Ditto
3) REPLIT_HEADERS is a constant, yes.
4) Smart.
5) I do understand that's shorter, I just feel like that's easier to read
6) Again, smart. I normally code in JS so I do `[y, z].includes(x)` but that works

**Comment by airportyh** [comment]
@DaInfLoop thank you for this. Would you mind adding a test for this as well?

**Comment by DaInfLoop** [comment]
Will do later on, currently not anywhere near my PC

**Review by noneofyourbusiness1415252 — COMMENTED** [review]
thanks for improving the code, but [`black`](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ATXAkJdAD2IimZxl1N_Wk8FsHgefxOIHALqp6RhP_xnyoXldfV1YScUiSyBLnd3CrUo3VhlTBuKuK20EvzEb_n67ZWjJfKntBbqkRkVO9-e3hY4-FaamL7esgtyTT_XDfyp0CeTdRejqE2USyv6fTo4zYq2c5PZSYtsJZEQJ9E05fOb-h2BR387_0L3nZsHFPl64yuSRktEW8QZ-EVKRppnhRMjhMeD9oTSBTbL7s5HA33ePmwuH8dQV5aRIne4xBX-1g2EYT5Mt1aqYfwxyPIXf-oBOg-VDHr1T6tbts01BSaC4dJeMSfJZjtlQylJDecXdddET-p66f-5ek4LTz80KANj3u4-oqX6vTY8FVbsg0ojldaT-LEPYSLusPVoFVmBZsgMwlleHr3MYX2nvV_9psRPFtsCLg8sSNs2vTavdynT2y9N-_0QvMvNi5pNsBMMM-M9cN2vpwJYr0iXvMkPmS3rlEptTzBlDff427MyP25MV-h13NdcRXx85UyE2tfyyxfeTuLirq48a7SKg-yt9PPGZMdilXH6DGccNMYEGEcBqRBbnU1z2ptQ3SCYPxoVPtCPh4EarYybB3ugjhXwWKowmwMlR30rnqO06jIWtBdfMDoL-Onj-CpcCtMk16gQaiZq3AH5uYeC1oBcAu_pClSJzehWJ2XWMhfFImHAFtE81BceyoAtGN_k2H6K7FsxCRiF0rNW2qKVK44PivcGBKVCatT51wbBxggzRFNxlYw7dwBbAAo_yGpqBYYmwsBKWytRhKruAAAAJIx9t4tn3N0AAd4E2AkAALul0PKxxGf7AgAAAAAEWVo=) is the "uncompromising" code formatter used in this repo and not `yapf`.
**Unintended behaviour** you would've spotted if formatting using `black`: `__all__` has to be set to `Sequence[str]`, so line 7 should be:
```py
__all__ = ("getUserInfo",)
```
It is the commas that define a `tuple`, not the brackets. Brackets are just used to delimit the tuple where needed (e.g., within a function call) / to make the code more readable.
Also, this might be intended but the attributes will never be set to `None` because all auth headers are always _present_ but are just set to `""` when unspecified

**Comment by DaInfLoop** [comment]
> thanks for improving the code, but [`black`](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ATXAkJdAD2IimZxl1N_Wk8FsHgefxOIHALqp6RhP_xnyoXldfV1YScUiSyBLnd3CrUo3VhlTBuKuK20EvzEb_n67ZWjJfKntBbqkRkVO9-e3hY4-FaamL7esgtyTT_XDfyp0CeTdRejqE2USyv6fTo4zYq2c5PZSYtsJZEQJ9E05fOb-h2BR387_0L3nZsHFPl64yuSRktEW8QZ-EVKRppnhRMjhMeD9oTSBTbL7s5HA33ePmwuH8dQV5aRIne4xBX-1g2EYT5Mt1aqYfwxyPIXf-oBOg-VDHr1T6tbts01BSaC4dJeMSfJZjtlQylJDecXdddET-p66f-5ek4LTz80KANj3u4-oqX6vTY8FVbsg0ojldaT-LEPYSLusPVoFVmBZsgMwlleHr3MYX2nvV_9psRPFtsCLg8sSNs2vTavdynT2y9N-_0QvMvNi5pNsBMMM-M9cN2vpwJYr0iXvMkPmS3rlEptTzBlDff427MyP25MV-h13NdcRXx85UyE2tfyyxfeTuLirq48a7SKg-yt9PPGZMdilXH6DGccNMYEGEcBqRBbnU1z2ptQ3SCYPxoVPtCPh4EarYybB3ugjhXwWKowmwMlR30rnqO06jIWtBdfMDoL-Onj-CpcCtMk16gQaiZq3AH5uYeC1oBcAu_pClSJzehWJ2XWMhfFImHAFtE81BceyoAtGN_k2H6K7FsxCRiF0rNW2qKVK44PivcGBKVCatT51wbBxggzRFNxlYw7dwBbAAo_yGpqBYYmwsBKWytRhKruAAAAJIx9t4tn3N0AAd4E2AkAALul0PKxxGf7AgAAAAAEWVo=) is the "uncompromising" code formatter used in this repo and not `yapf`. **Unintended behaviour** you would've spotted if formatting using `black`: `__all__` has to be set to `Sequence[str]`, so line 7 should be:
> 
> ```python
> __all__ = ("getUserInfo",)
> ```
> 
> It is the commas that define a `tuple`, not the brackets. Brackets are just used to delimit the tuple where needed (e.g., within a function call) / to make the code more readable. Also, this might be intended but the attributes will never be set to `None` because all auth headers are always _present_ but are just set to `""` when unspecified

and of course i had to see this after i added the tests 🙄

**Comment by DaInfLoop** [comment]
@airportyh added tests 👍

**Comment by airportyh** [comment]
> @airportyh added tests 👍

It's [failing in CI](https://replit.semaphoreci.com/jobs/734b73a2-82ca-408a-ae37-2de1f61d5a19) for some reason. I may be able to take a look this week.

**Comment by airportyh** [comment]
I ran the tests are get:
```
$ poetry run coverage run -m unittest
Warning: error initializing database. Replit DB is not configured.
EEFE
======================================================================
ERROR: tests.test_database (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_database
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/toby/replit/replit-py/tests/test_database.py", line 7, in <module>
    from replit.database import AsyncDatabase, Database
  File "/home/toby/replit/replit-py/src/replit/__init__.py", line 15, in <module>
    from .auth import getUserInfo
ImportError: cannot import name 'getUserInfo' from 'replit.auth' (/home/toby/replit/replit-py/src/replit/auth/__init__.py)


======================================================================
ERROR: tests.test_identity (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_identity
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/toby/replit/replit-py/tests/test_identity.py", line 8, in <module>
    import replit.identity
  File "/home/toby/replit/replit-py/src/replit/__init__.py", line 15, in <module>
    from .auth import getUserInfo
ImportError: cannot import name 'getUserInfo' from 'replit.auth' (/home/toby/replit/replit-py/src/replit/auth/__init__.py)


======================================================================
ERROR: test_check_user_data (tests.test_replauth.TestAuth)
Test to see if the user data is correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/toby/replit/replit-py/tests/test_replauth.py", line 49, in test_check_user_data
    self.assertDictEqual(user.__dict__, {
AttributeError: 'NoneType' object has no attribute '__dict__'

======================================================================
FAIL: test_check_proper_auth (tests.test_replauth.TestAuth)
Test get_user_info.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/toby/replit/replit-py/tests/test_replauth.py", line 40, in test_check_proper_auth
    self.assertIsInstance(authed, User)
AssertionError: None is not an instance of <class 'replit.auth.User'>

----------------------------------------------------------------------
Ran 4 tests in 0.001s
```
Some of them are probably trivial errors, like matching the spelling of `getUserInfo` and `get_user_info`.

**Comment by DaInfLoop** [comment]
Ah I see. Sorry for the last response aswell, haven't checked GH in a while. Will fix.

**Comment by airportyh** [comment]
I am going to close this due to inactivity.

**Pull request closed without merging**
