### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by techpixel**
In the README, I find that this is a little bit misleading. 
> *A Flask–based application framework for accelerating development on the platform.*

This change accurately represents the feature as an interface to replit:
> _A Flask interface to Replit's User Authetication service_

### CODE REVIEW

**Comment by Scoder12** [comment]
it's more than just auth though. can you elaborate on what is misleading?

**Comment by techpixel** [comment]
From what I can gather from the documentation, the "web" part only consists of an interface to replit auth and a few helper /wrapper functions.

**Comment by Scoder12** [comment]
Well "vague" is different from "misleading." I think the current wording is sufficient to "draw a user in." While I'm willing to change it, I think that your wording doesn't cover the full scope of `replit.web`.

**Comment by techpixel** [comment]
How about:
> _Tools and utilities for Flask Web Development, including an interface to Replit's User Authetication service_

It points to the wrappers and helper functions while also mentioning the Auth interface.

**Comment by Scoder12** [comment]
Sounds good. If you update that sentence as you mentioned I'll merge

**Comment by techpixel** [comment]
Sentence was updated and is ready to merge.

**Comment by techpixel** [comment]
Will this merge?

**Comment by lafkpages** [comment]
Will it?

**Comment by techpixel** [comment]
It appears this library stopped getting updates near the time this PR was made, so likely not.

**Review by blast-hardcheese — APPROVED** [review]
Looks great! Sorry for the lack of response up until now!

**Pull request merged**
