### PR TITLE
Make async delete raise key error on 404

### PR DESCRIPTION
**Pull request by Codemonkey51**
Make async delete raise key error if it runs into a non-existent key

### CODE REVIEW

**Comment by Codemonkey51** [comment]
I added another commit but it isn't showing up for me on this pr

**Review by Scoder12 — CHANGES_REQUESTED** [review]
Please fix the flake8 error and you're good to go!

**Comment by Codemonkey51** [comment]
> Please fix the flake8 error and you're good to go!

ok i wasnt seeing the tests before so i can do that now

**Comment by Codemonkey51** [comment]
aghhhh i cant get the docstring working @Scoder12 could you help

**Comment by Codemonkey51** [comment]
@kochman now all tests are failing due to secret not found

**Comment by kochman** [comment]
> @kochman now all tests are failing due to secret not found

@Codemonkey51 You'll want to merge master into your branch; the secret has been renamed

**Comment by Codemonkey51** [comment]
> > @kochman now all tests are failing due to secret not found
> 
> @Codemonkey51 You'll want to merge master into your branch; the secret has been renamed

Ok will do that rn

**Comment by Scoder12** [comment]
LGTM, thanks!

**Pull request merged**
