### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by cxstles**
Why
===

It was required that's why.

What changed
============

New version.

### CODE REVIEW

**Comment by cdmistman** [comment]
hey, when you say "it was required that's why" - what do you mean by this? what required it? in what context was it required?

**Comment by reciprocated** [comment]
> hey, when you say "it was required that's why" - what do you mean by this? what required it? in what context was it required?

I made another PR that would require this to be changed and updated.

**Comment by cdmistman** [comment]
image

are @cxstles and @reciprocated the same person?

closing because this will happen either way, but possibly as a major or minor version bump.

**Comment by reciprocated** [comment]
> image
> are @cxstles and @reciprocated the same person?
> 
> closing because this will happen either way, but possibly as a major or minor version bump.

mhm, yeah I'm @cxstles.

**Pull request closed without merging**
