### PR TITLE
Add CLI for Repl DB interactions

### PR DESCRIPTION
**Pull request by frissyn**
Uses [`click`](https://click.palletsprojects.com/en/7.x/) to implement a simple CLI that allows users to interact with their Repl's DB from the shell / command line. Currently has 4 commands, I forgot to add the nuke command before opening the PR :| 

It also uses `replit.py`'s own termutils for coloring! The screenshot below is the interactive example I wrote up which you can find [at this Repl](https://repl.it/@IreTheKID/Repl-DB-CLI#main.py).

screenshot

### CODE REVIEW

**Comment by Codemonkey51** [comment]
Great idea!

**Comment by IreTheKID** [comment]
It's on the TODO in the `__init__.py` and I was bored so... ¯\\\_(ツ)\_ /¯

**Comment by Codemonkey51** [comment]
Lmao

**Comment by JDOG787** [comment]
Sounds cool!

**Comment by InterestingBrainPoops** [comment]
Interesting!

**Comment by IreTheKID** [comment]
Just added the nuke and del commands, along with increased error handling and context coloring for the CLI outputs!

demo2

**Comment by InterestingBrainPoops** [comment]
Is there a help cmd?

**Comment by IreTheKID** [comment]
You can run `repldb --help` or `repldb [CMD] --help` for any command by default.

**Comment by Codemonkey51** [comment]
Hello ire, I just saw that you check is_admin for nuke, but not everyone will set that. it also seems that that's a bit useless since someone as a visitor on the repl gets a blank repldb and can't interact with the real one.

**Comment by IreTheKID** [comment]
Hmm... I guess it is a bit redundant, I'll remove it then. I didn't know that visitors of the repl would get a blank one 😓

**Comment by Codemonkey51** [comment]
Ok, I was just letting you know :)

**Comment by IreTheKID** [comment]
@Codemonkey51 ok, I fixed it, thanks :)

**Comment by IreTheKID** [comment]
@Scoder12 can you take a look when you can? It's mostly done now.

**Comment by JDOG787** [comment]
Is this only for python repls then?

**Comment by InterestingBrainPoops** [comment]
That would make sense

**Comment by IreTheKID** [comment]
This is `replit.py` after all @JDOG787

**Comment by IreTheKID** [comment]
Merged the most recent commit: #25

**Comment by IreTheKID** [comment]
@Scoder12 @kochman The docstring checks don't *have* to pass right? The multi-line strings under each `click` function are there for the sake of `--help` not docuementation.

**Comment by Codemonkey51** [comment]
> @Scoder12 @kochman The docstring checks don't _have_ to pass right? The multi-line strings under each `click` function are there for the sake of `--help` not documentation.

I think they do :/ they are *required* for merge

**Comment by IreTheKID** [comment]
Hmm, guess I'll have to write some then :|

**Comment by IreTheKID** [comment]
Flake8  is such a pain holy moly

**Comment by Codemonkey51** [comment]
> Flake8 is such a pain holy moly, no way that commit failed :(

Took me 2 months to find and error, and by then other stuff changed, breaking it

**Comment by IreTheKID** [comment]
That's the best I can do with flake8 ¯\\\_(ツ)\_ /¯

**Comment by Codemonkey51** [comment]
@IreTheKID would you be ok with me editing ur pr to fix the error?

**Comment by IreTheKID** [comment]
Sure, do whatever

**Comment by Codemonkey51** [comment]
@IreTheKID do you *need* the eval? It's unsafe and it breaks flake 8

**Comment by IreTheKID** [comment]
I don't *need* it per se, but `ast.literal_eval()` is trash so I guess you could just `str()` it and remove "Dynamically Typed" from the dosctring if you want.

**Comment by Codemonkey51** [comment]
> I don't _need_ it per se, but `ast.literal_eval()` is trash so I guess you could just `str()` it and remove "Dynamically Typed" from the dosctring if you want.

That should work, and also fix flake8 errors

**Comment by Codemonkey51** [comment]
@kochman seems like there is an issue with some mypy package installs causing this to fail

**Comment by IreTheKID** [comment]
:(

**Comment by Codemonkey51** [comment]
@kochman seems like there is an issue with some mypy packages 

> :(

Oof, the moment flake8 is fixed unittests and or mypy commit fail

**Comment by IreTheKID** [comment]
@Codemonkey51 It passed 🎉

**Comment by Codemonkey51** [comment]
COOL! I'll request a review from @kochman then it should be good to go. (I'm no really sure if I'm allowed to merge on my own :/)

**Review by Codemonkey51 — APPROVED** [review]
Looks good! (Idk if I'm allowed to merge :/)

**Comment by IreTheKID** [comment]
Ok, thanks!

**Comment by kennethreitz42** [comment]
Merged into PR #28

**Comment by frissyn** [comment]
@kennethreitz42 thanks!

**Comment by frissyn** [comment]
Closing PR, as its contents were included in #28

**Pull request closed without merging**
